package graduation.money.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "add_money")
public class AddMoney extends BaseDTO {

     public static final String FIELD_ADD_ID = "addId";
     public static final String FIELD_MONEY = "money";
     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_REMAKE = "remake";
     public static final String FIELD_ADD_TYPE = "addType";


     @Id
     @GeneratedValue
     private Long addId;

     private Float money;

     private Long userId;

     @NotEmpty
     @Length(max = 30)
     private String orderId;

     @Length(max = 150)
     private String remake;

     private Long addType; //未处理：0，已处理：1


     public void setAddId(Long addId){
         this.addId = addId;
     }

     public Long getAddId(){
         return addId;
     }

     public void setMoney(Float money){
         this.money = money;
     }

     public Float getMoney(){
         return money;
     }

     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     public void setOrderId(String orderId){
         this.orderId = orderId;
     }

     public String getOrderId(){
         return orderId;
     }

     public void setRemake(String remake){
         this.remake = remake;
     }

     public String getRemake(){
         return remake;
     }

     public void setAddType(Long addType){
         this.addType = addType;
     }

     public Long getAddType(){
         return addType;
     }

     }
