package graduation.money.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable=true)
@Table(name = "balance_driver")
public class BalanceDriver extends BaseDTO {

     public static final String FIELD_BD_ID = "bdId";
     public static final String FIELD_MONEY = "money";
     public static final String FIELD_DRIVER_ID = "driverId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_TYPE = "type";


     @Id
     @GeneratedValue
     private Long bdId;

     private Float money;

     private Long driverId;

    @NotEmpty
    @Length(max = 30)
    private String orderId;

     private Long type; //完成订单：0，兑换现金：1，提现：2


     public void setBdId(Long bdId){
         this.bdId = bdId;
     }

     public Long getBdId(){
         return bdId;
     }

     public void setMoney(Float money){
         this.money = money;
     }

     public Float getMoney(){
         return money;
     }

     public void setDriverId(Long driverId){
         this.driverId = driverId;
     }

     public Long getDriverId(){
         return driverId;
     }

     public void setOrderId(String orderId){
         this.orderId = orderId;
     }

     public String getOrderId(){
         return orderId;
     }

     public void setType(Long type){
         this.type = type;
     }

     public Long getType(){
         return type;
     }

     }
