package graduation.money.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable=true)
@Table(name = "balance_user")
public class BalanceUser extends BaseDTO {

     public static final String FIELD_BU_ID = "buId";
     public static final String FIELD_MONEY = "money";
     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_TYPE = "type";


     @Id
     @GeneratedValue
     private Long buId;

     private Float money;

     private Long userId;

    @NotEmpty
    @Length(max = 30)
    private String orderId;

     private Long type; //充值:0,下单：1，提现：2


     public void setBuId(Long buId){
         this.buId = buId;
     }

     public Long getBuId(){
         return buId;
     }

     public void setMoney(Float money){
         this.money = money;
     }

     public Float getMoney(){
         return money;
     }

     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     public void setOrderId(String orderId){
         this.orderId = orderId;
     }

     public String getOrderId(){
         return orderId;
     }

     public void setType(Long type){
         this.type = type;
     }

     public Long getType(){
         return type;
     }

     }
