package graduation.credit.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "credit_user")
public class CreditUser extends BaseDTO {

    public static final String FIELD_CREDIT_ID = "creditId";
    public static final String FIELD_USER_ID = "userId";
    public static final String FIELD_ORDER_ID = "orderId";
    public static final String FIELD_NUM = "num";
    public static final String FIELD_CREDIT_TYPE = "creditType";
    public static final String FIELD_CREATE_TIME = "createTime";


    @Id
    @GeneratedValue
    private Long creditId;

    private Long userId;

    private Long orderId;

    private Long num;

    private Long creditType;

    private Date createTime;


    public void setCreditId(Long creditId) {
        this.creditId = creditId;
    }

    public Long getCreditId() {
        return creditId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public Long getNum() {
        return num;
    }

    public void setNum(Long num) {
        this.num = num;
    }

    public void setCreditType(Long creditType) {
        this.creditType = creditType;
    }

    public Long getCreditType() {
        return creditType;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

}
