package graduation.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "address")
public class Address extends BaseDTO {

     public static final String FIELD_ADDRESS_ID = "addressId";
     public static final String FIELD_PROVINCE = "province";
     public static final String FIELD_CITY = "city";
     public static final String FIELD_TOWN = "town";
     public static final String FIELD_ADDRESS_DETAIL = "addressDetail";
     public static final String FIELD_USER_ID = "userId";


     @Id
     @GeneratedValue
     private Long addressId;

     @NotEmpty
     @Length(max = 10)
     private String province;

     @NotEmpty
     @Length(max = 10)
     private String city;

     @NotEmpty
     @Length(max = 10)
     private String town;

     @NotEmpty
     @Length(max = 500)
     private String addressDetail;

     private Long userId;


     public void setAddressId(Long addressId){
         this.addressId = addressId;
     }

     public Long getAddressId(){
         return addressId;
     }

     public void setProvince(String province){
         this.province = province;
     }

     public String getProvince(){
         return province;
     }

     public void setCity(String city){
         this.city = city;
     }

     public String getCity(){
         return city;
     }

     public void setTown(String town){
         this.town = town;
     }

     public String getTown(){
         return town;
     }

     public void setAddressDetail(String addressDetail){
         this.addressDetail = addressDetail;
     }

     public String getAddressDetail(){
         return addressDetail;
     }

     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     }
