package graduation.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "car_repair")
public class CarRepair extends BaseDTO {

     public static final String FIELD_REPAIR_ID = "repairId";
     public static final String FIELD_REPAIR_TIME = "repairTime";
     public static final String FIELD_REPAIR_CONTENT = "repairContent";
     public static final String FIELD_DRIVER_ID = "driverId";
     public static final String FIELD_REPAIR_COMPANY = "repairCompany";
     public static final String FIELD_PLATE_NUMBER = "plateNumber";


     @Id
     @GeneratedValue
     private Long repairId;

     @NotEmpty
     @Length(max = 15)
     private String repairTime;

     @NotEmpty
     @Length(max = 150)
     private String repairContent;

     private Long driverId;

     @NotEmpty
     @Length(max = 30)
     private String repairCompany;

     @NotEmpty
     @Length(max = 20)
     private String plateNumber;


     public void setRepairId(Long repairId){
         this.repairId = repairId;
     }

     public Long getRepairId(){
         return repairId;
     }

     public void setRepairTime(String repairTime){
         this.repairTime = repairTime;
     }

     public String getRepairTime(){
         return repairTime;
     }

     public void setRepairContent(String repairContent){
         this.repairContent = repairContent;
     }

     public String getRepairContent(){
         return repairContent;
     }

     public void setDriverId(Long driverId){
         this.driverId = driverId;
     }

     public Long getDriverId(){
         return driverId;
     }

     public void setRepairCompany(String repairCompany){
         this.repairCompany = repairCompany;
     }

     public String getRepairCompany(){
         return repairCompany;
     }

     public void setPlateNumber(String plateNumber){
         this.plateNumber = plateNumber;
     }

     public String getPlateNumber(){
         return plateNumber;
     }

     }
