package graduation.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "driver_car")
public class DriverCar extends BaseDTO {

     public static final String FIELD_CAR_ID = "carId";
     public static final String FIELD_CAR_TYPE = "carType";
     public static final String FIELD_PLATE_NUMBER = "plateNumber";
     public static final String FIELD_CAR_LONG = "carLong";
     public static final String FIELD_CAR_HEIGHT = "carHeight";
     public static final String FIELD_CAR_WIDE = "carWide";
     public static final String FIELD_CAR_AGE = "carAge";
     public static final String FIELD_CAR_TONNAGE = "carTonnage";
     public static final String FIELD_DRIVER_ID = "driverId";


     @Id
     @GeneratedValue
     private Long carId;

     @NotEmpty
     @Length(max = 10)
     private String carType; //车辆类型

     @NotEmpty
     @Length(max = 20)
     private String plateNumber; //车牌

     @NotEmpty
     @Length(max = 11)
     private String carLong;

     @NotEmpty
     @Length(max = 11)
     private String carHeight;

     @NotEmpty
     @Length(max = 11)
     private String carWide;

     @NotEmpty
     @Length(max = 11)
     private String carAge; //车龄

     @NotEmpty
     @Length(max = 11)
     private Float carTonnage; //载重

     private Long driverId; //司机id


     public void setCarId(Long carId){
         this.carId = carId;
     }

     public Long getCarId(){
         return carId;
     }

     public void setCarType(String carType){
         this.carType = carType;
     }

     public String getCarType(){
         return carType;
     }

     public void setPlateNumber(String plateNumber){
         this.plateNumber = plateNumber;
     }

     public String getPlateNumber(){
         return plateNumber;
     }

     public void setCarLong(String carLong){
         this.carLong = carLong;
     }

     public String getCarLong(){
         return carLong;
     }

     public void setCarHeight(String carHeight){
         this.carHeight = carHeight;
     }

     public String getCarHeight(){
         return carHeight;
     }

     public void setCarWide(String carWide){
         this.carWide = carWide;
     }

     public String getCarWide(){
         return carWide;
     }

     public void setCarAge(String carAge){
         this.carAge = carAge;
     }

     public String getCarAge(){
         return carAge;
     }

    public Float getCarTonnage() {
        return carTonnage;
    }

    public void setCarTonnage(Float carTonnage) {
        this.carTonnage = carTonnage;
    }

    public void setDriverId(Long driverId){
         this.driverId = driverId;
     }

     public Long getDriverId(){
         return driverId;
     }

     }
