package graduation.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "evaluate")
public class Evaluate extends BaseDTO {

    public static final String FIELD_EVALUATE_ID = "evaluateId";
    public static final String FIELD_CONTENT = "content";
    public static final String FIELD_ORDER_ID = "orderId";
    public static final String FIELD_SERVICE_SCORE = "serviceScore";
    public static final String FIELD_USER_ID = "userId";
    public static final String FIELD_DRIVER_ID = "driverId";
    public static final String FIELD_EVALUATE_TYPE = "evaluateType";


    @Id
    @GeneratedValue
    private Long evaluateId;

    @NotEmpty
    @Length(max = 500)
    private String content; //内容

    @NotEmpty
    @Length(max = 20)
    private String orderId; //订单编号

    private Long serviceScore; //服务评分

    private Long userId; //用户id

    private Long driverId; //司机Id

    private Long evaluateType;//用户的评价:0,司机的评价:1


    public Long getEvaluateId() { return evaluateId; }

    public void setEvaluateId(Long evaluateId) { this.evaluateId = evaluateId; }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContent() {
        return content;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setServiceScore(Long serviceScore) {
        this.serviceScore = serviceScore;
    }

    public Long getServiceScore() {
        return serviceScore;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    public Long getDriverId() {
        return driverId;
    }

    public Long getEvaluateType() {
        return evaluateType;
    }

    public void setEvaluateType(Long evaluateType) {
        this.evaluateType = evaluateType;
    }
}
