package graduation.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.List;

@ExtensionAttribute(disable=true)
@Table(name = "goods_collect")
public class GoodsCollect extends BaseDTO {

     public static final String FIELD_COLLECT_ID = "collectId";
     public static final String FIELD_COLLECT_NAME = "collectName";
     public static final String FIELD_COLLECT_TYPE = "collectType";
     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_COLLECT_SATTUS = "collectStatus";


     @Id
     @GeneratedValue
     private Long collectId;

     @NotEmpty
     @Length(max = 50)
     private String collectName;

     @NotEmpty
     @Length(max = 10)
     private String collectType;

     @Children
     @Transient
     private List<Goods> goodsList;

     private Long userId;

     private Long collectStatus;


     public void setCollectId(Long collectId){
         this.collectId = collectId;
     }

     public Long getCollectId(){
         return collectId;
     }

     public void setCollectName(String collectName){
         this.collectName = collectName;
     }

     public String getCollectName(){
         return collectName;
     }

     public void setCollectType(String collectType){
         this.collectType = collectType;
     }

     public String getCollectType(){
         return collectType;
     }

     public List<Goods> getGoodsList() { return goodsList; }

     public void setGoodsList(List<Goods> goodsList) { this.goodsList = goodsList; }

     public Long getUserId() { return userId; }

     public void setUserId(Long userId) { this.userId = userId; }

     public Long getCollectStatus() {
          return collectStatus;
     }

     public void setCollectStatus(Long collectStatus) {
          this.collectStatus = collectStatus;
     }
}
