package graduation.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "user_complain")
public class UserComplain extends BaseDTO {

     public static final String FIELD_COMPLAIN_ID = "complainId";
     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_DRIVER_ID = "driverId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_REAL_NAME = "realName";
     public static final String FIELD_PHONE = "phone";
     public static final String FIELD_COMPLAIN_REASON = "complainReason";
     public static final String FIELD_COMPLAIN_CONTENT = "complainContent";
     public static final String FIELD_COMPLAIN_STATUS = "complainStatus";


     @Id
     @GeneratedValue
     private Long complainId; //id

     private Long userId; //用户编号

     private Long driverId; //司机编号

     private Long orderId; //订单编号

     @NotEmpty
     @Length(max = 20)
     private String realName; //联系人

     @NotEmpty
     @Length(max = 12)
     private String phone; //联系电话

     @NotEmpty
     @Length(max = 50)
     private String complainReason; //投诉原因

     @NotEmpty
     @Length(max = 500)
     private String complainContent; //投诉内容

     private Long complainStatus; //投诉状态,初始:0,结束:1


     public void setComplainId(Long complainId){
         this.complainId = complainId;
     }

     public Long getComplainId(){
         return complainId;
     }

     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     public void setDriverId(Long driverId){
         this.driverId = driverId;
     }

     public Long getDriverId(){
         return driverId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setRealName(String realName){
         this.realName = realName;
     }

     public String getRealName(){
         return realName;
     }

     public void setPhone(String phone){
         this.phone = phone;
     }

     public String getPhone(){
         return phone;
     }

     public void setComplainReason(String complainReason){
         this.complainReason = complainReason;
     }

     public String getComplainReason(){
         return complainReason;
     }

     public void setComplainContent(String complainContent){
         this.complainContent = complainContent;
     }

     public String getComplainContent(){
         return complainContent;
     }

     public void setComplainStatus(Long complainStatus){
         this.complainStatus = complainStatus;
     }

     public Long getComplainStatus(){
         return complainStatus;
     }

     }
