package graduation.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "o_car_type")
public class OCarType extends BaseDTO {

     public static final String FIELD_CAR_ID = "carId";
     public static final String FIELD_CAR_TYPE = "carType";
     public static final String FIELD_CAR_LONG = "carLong";
     public static final String FIELD_CAR_WIDTH = "carWidth";
     public static final String FIELD_CAR_HEIGHT = "carHeight";
     public static final String FIELD_START_PRICE = "startPrice";
     public static final String FIELD_ADD_PRICE = "addPrice";
     public static final String FIELD_START_DISTANCE = "startDistance";
     public static final String FIELD_START_GOODS_WEIGHT = "startGoodsWeight";
     public static final String FIELD_END_GOODS_WEIGHT = "endGoodsWeight";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_STATUS = "status";


     private Long carId;

     @NotEmpty
     @Length(max = 50)
     private String carType; //卡车类型

     @NotEmpty
     @Length(max = 11)
     private String carLong; //卡车长

     @NotEmpty
     @Length(max = 11)
     private String carWidth; //卡车宽

     @NotEmpty
     @Length(max = 11)
     private String carHeight; //卡车高

     @NotEmpty
     @Length(max = 11)
     private String startPrice; //起步价

     @NotEmpty
     @Length(max = 11)
     private String addPrice; //每公里加价

     @NotEmpty
     @Length(max = 11)
     private String startDistance; //默认不加价距离

     @NotEmpty
     @Length(max = 11)
     private String startGoodsWeight; //起始吨位

     @NotEmpty
     @Length(max = 11)
     private String endGoodsWeight; //最大吨位

     @Length(max = 500)
     private String description; //描述

     @Length(max = 30)
     private String status; //状态


     public void setCarId(Long carId){
         this.carId = carId;
     }

     public Long getCarId(){
         return carId;
     }

     public void setCarType(String carType){
         this.carType = carType;
     }

     public String getCarType(){
         return carType;
     }

     public void setCarLong(String carLong){
         this.carLong = carLong;
     }

     public String getCarLong(){
         return carLong;
     }

     public void setCarWidth(String carWidth){
         this.carWidth = carWidth;
     }

     public String getCarWidth(){
         return carWidth;
     }

     public void setCarHeight(String carHeight){
         this.carHeight = carHeight;
     }

     public String getCarHeight(){
         return carHeight;
     }

     public void setStartPrice(String startPrice){
         this.startPrice = startPrice;
     }

     public String getStartPrice(){
         return startPrice;
     }

     public void setAddPrice(String addPrice){
         this.addPrice = addPrice;
     }

     public String getAddPrice(){
         return addPrice;
     }

     public void setStartDistance(String startDistance){
         this.startDistance = startDistance;
     }

     public String getStartDistance(){
         return startDistance;
     }

     public void setStartGoodsWeight(String startGoodsWeight){
         this.startGoodsWeight = startGoodsWeight;
     }

     public String getStartGoodsWeight(){
         return startGoodsWeight;
     }

     public void setEndGoodsWeight(String endGoodsWeight){
         this.endGoodsWeight = endGoodsWeight;
     }

     public String getEndGoodsWeight(){
         return endGoodsWeight;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     }
