package graduation.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "o_goods_collect")
public class OGoodsCollect extends BaseDTO {

     public static final String FIELD_COLLECT_ID = "collectId";
     public static final String FIELD_COLLECT_NAME = "collectName";
     public static final String FIELD_COLLECT_TYPE = "collectType";
     public static final String FIELD_USER_ID = "userId";


     private Long collectId;

     @NotEmpty
     @Length(max = 50)
     private String collectName;

     @NotEmpty
     @Length(max = 10)
     private String collectType;

     private Long userId;


     public void setCollectId(Long collectId){
         this.collectId = collectId;
     }

     public Long getCollectId(){
         return collectId;
     }

     public void setCollectName(String collectName){
         this.collectName = collectName;
     }

     public String getCollectName(){
         return collectName;
     }

     public void setCollectType(String collectType){
         this.collectType = collectType;
     }

     public String getCollectType(){
         return collectType;
     }

     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     }
