package graduation.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "o_goods")
public class OGoods extends BaseDTO {

     public static final String FIELD_GOODS_ID = "goodsId";
     public static final String FIELD_GOODS_NAME = "goodsName";
     public static final String FIELD_GOODS_NUM = "goodsNum";
     public static final String FIELD_GOODS_TYPE = "goodsType";
     public static final String FIELD_GOODS_QUALITY = "goodsQuality";
     public static final String FIELD_GOODS_REMARK = "goodsRemark";
     public static final String FIELD_COLLECT_ID = "collectId";


     private Long goodsId;

     @NotEmpty
     @Length(max = 100)
     private String goodsName;

     private Long goodsNum;

     @NotEmpty
     @Length(max = 50)
     private String goodsType;

     @NotEmpty
     @Length(max = 100)
     private String goodsQuality;

     @Length(max = 500)
     private String goodsRemark; //备注

     private Long collectId;


     public void setGoodsId(Long goodsId){
         this.goodsId = goodsId;
     }

     public Long getGoodsId(){
         return goodsId;
     }

     public void setGoodsName(String goodsName){
         this.goodsName = goodsName;
     }

     public String getGoodsName(){
         return goodsName;
     }

     public void setGoodsNum(Long goodsNum){
         this.goodsNum = goodsNum;
     }

     public Long getGoodsNum(){
         return goodsNum;
     }

     public void setGoodsType(String goodsType){
         this.goodsType = goodsType;
     }

     public String getGoodsType(){
         return goodsType;
     }

     public void setGoodsQuality(String goodsQuality){
         this.goodsQuality = goodsQuality;
     }

     public String getGoodsQuality(){
         return goodsQuality;
     }

     public void setGoodsRemark(String goodsRemark){
         this.goodsRemark = goodsRemark;
     }

     public String getGoodsRemark(){
         return goodsRemark;
     }

     public void setCollectId(Long collectId){
         this.collectId = collectId;
     }

     public Long getCollectId(){
         return collectId;
     }

     }
