package graduation.order.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "user_order")
public class UserOrder extends BaseDTO {

    public static final String FIELD_ORDER_ID = "orderId";
    public static final String FIELD_USER_ID = "userId";
    public static final String FIELD_COLLECT_ID = "collectId";
    public static final String FIELD_START_ADDRESS = "startAddress";
    public static final String FIELD_END_ADDRESS = "endAddress";
    public static final String FIELD_CAR_ID = "carId";
    public static final String FIELD_CONTACT_NAME = "contactName";
    public static final String FIELD_CONTACT_PHONE = "contactPhone";
    public static final String FIELD_ORDER_PRICE = "orderPrice";
    public static final String FIELD_DRIVER_ID = "driverId";
    public static final String FIELD_ORDER_REMAKE = "orderRemake";
    public static final String FIELD_ORDER_STATUS = "orderStatus";
    public static final String FIELD_START_ADDRESS_ID = "startAddressId";


    @Id
    @GeneratedValue
    private Long orderId; //订单编号

    private Long userId; //用户id

    private Long collectId; //货物id

    private Long driverId;//司机id

    private Long orderStatus;//订单状态，初始化：0,交易完成：1,拒绝付款：2

    @NotEmpty
    @Length(max = 50)

    private String startAddress; //起点

    @NotEmpty
    @Length(max = 50)
    private String endAddress; //目的地

    private Long carId; //卡车id

    @NotEmpty
    @Length(max = 50)
    private String contactName; //联系人姓名

    @NotEmpty
    @Length(max = 12)
    private String contactPhone; //联系人电话

    @NotEmpty
    @Length(max = 20)
    private String orderPrice; //订单价格

    @Length(max = 500)
    private String orderRemake; //备注

    private Long startAddressId;


    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setCollectId(Long collectId) {
        this.collectId = collectId;
    }

    public Long getCollectId() {
        return collectId;
    }

    public void setStartAddress(String startAddress) {
        this.startAddress = startAddress;
    }

    public String getStartAddress() {
        return startAddress;
    }

    public void setEndAddress(String endAddress) {
        this.endAddress = endAddress;
    }

    public String getEndAddress() {
        return endAddress;
    }

    public void setCarId(Long carId) {
        this.carId = carId;
    }

    public Long getCarId() {
        return carId;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setOrderPrice(String orderPrice) {
        this.orderPrice = orderPrice;
    }

    public String getOrderPrice() {
        return orderPrice;
    }

    public void setOrderRemake(String orderRemake) {
        this.orderRemake = orderRemake;
    }

    public String getOrderRemake() {
        return orderRemake;
    }

    public Long getDriverId() { return driverId; }

    public void setDriverId(Long driverId) { this.driverId = driverId; }

    public Long getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(Long orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Long getStartAddressId() {
        return startAddressId;
    }

    public void setStartAddressId(Long startAddressId) {
        this.startAddressId = startAddressId;
    }
}
