package gzt.ora21991.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable=true)
@Table(name = "base_address_name_b")
public class AddressName extends BaseDTO {

     public static final String FIELD_ADDRESS_ID = "addressId";
     public static final String FIELD_ADDRESS_NAME = "addressName";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_TYPE = "type";
     public static final String FIELD_PARENT_ADDRESS_ID = "parentAddressId";
     public static final String FIELD_AREA_CODE = "areaCode";


     @Id
     @GeneratedValue
     private Long addressId;

     @NotEmpty
     @Length(max = 100)
     private String addressName;

     @Length(max = 240)
     private String description;

     @NotEmpty
     @Length(max = 50)
     private String type;

     private Long parentAddressId;

     @Length(max = 20)
     private String areaCode;


     public void setAddressId(Long addressId){
         this.addressId = addressId;
     }

     public Long getAddressId(){
         return addressId;
     }

     public void setAddressName(String addressName){
         this.addressName = addressName;
     }

     public String getAddressName(){
         return addressName;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setType(String type){
         this.type = type;
     }

     public String getType(){
         return type;
     }

     public void setParentAddressId(Long parentAddressId){
         this.parentAddressId = parentAddressId;
     }

     public Long getParentAddressId(){
         return parentAddressId;
     }

     public void setAreaCode(String areaCode){
         this.areaCode = areaCode;
     }

     public String getAreaCode(){
         return areaCode;
     }

     }
