package gzt.ora21991.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "hcrm_customer")
public class Customer extends BaseDTO {

    public static final String FIELD_CUSTOMER_ID = "customerId";
    public static final String FIELD_CUSTOMER_CODE = "customerCode";
    public static final String FIELD_FULL_NAME = "fullName";
    public static final String FIELD_ENGLISH_NAME = "englishName";
    public static final String FIELD_CREDIT_CODE = "creditCode";
    public static final String FIELD_DUTY_PARAGRAPH = "dutyParagraph";
    public static final String FIELD_CUSTOMER_AMOUNT = "customerAmount";
    public static final String FIELD_PARENT_CUSTOMERS_ID = "parentCustomersId";
    public static final String FIELD_ADDRESS_COUNTRY = "addressCountry";
    public static final String FIELD_ADDRESS_PROVINCE = "addressProvince";
    public static final String FIELD_ADDRESS_CITY = "addressCity";
    public static final String FIELD_ADDRESS_ZONE = "addressZone";
    public static final String FIELD_ADDRESS_DETAILS = "addressDetails";
    public static final String FIELD_PHONE = "phone";
    public static final String FIELD_WEBSITE = "website";
    public static final String FIELD_IS_LISTED = "isListed";
    public static final String FIELD_OTHER_DESCRIPTION = "otherDescription";
    public static final String FIELD_PARENT_CUSTOMER_NAME = "parentCustomerName";


    @Id
    @GeneratedValue
    private Long customerId;

    @NotEmpty
    @Length(max = 30)
    private String customerCode;

    @NotEmpty
    @Length(max = 500)
    private String fullName;

    @Length(max = 500)
    private String englishName;

    @Length(max = 100)
    private String creditCode;

    @Length(max = 100)
    private String dutyParagraph;

    private Long customerAmount;

    private Long parentCustomersId;

    @Length(max = 50)
    private String addressCountry;

    @Length(max = 50)
    private String addressProvince;

    @Length(max = 50)
    private String addressCity;

    @Length(max = 50)
    private String addressZone;

    @Length(max = 500)
    private String addressDetails;

    @Length(max = 30)
    private String phone;

    @Length(max = 300)
    private String website;

    @Length(max = 1)
    private String isListed;

    @Length(max = 3000)
    private String otherDescription;

    @Children
    @Transient
    private List<Product> products;

    @Children
    @Transient
    private List<CustomerContact> customerContacts;

    @Transient
    private String parentCustomerName;

    @Transient
    private String name;

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    public String getCustomerCode() {
        return customerCode;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getFullName() {
        return fullName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getEnglishName() {
        return englishName;
    }

    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    public String getCreditCode() {
        return creditCode;
    }

    public void setDutyParagraph(String dutyParagraph) {
        this.dutyParagraph = dutyParagraph;
    }

    public String getDutyParagraph() {
        return dutyParagraph;
    }

    public void setCustomerAmount(Long customerAmount) {
        this.customerAmount = customerAmount;
    }

    public Long getCustomerAmount() {
        return customerAmount;
    }

    public void setParentCustomersId(Long parentCustomersId) {
        this.parentCustomersId = parentCustomersId;
    }

    public Long getParentCustomersId() {
        return parentCustomersId;
    }

    public void setAddressCountry(String addressCountry) {
        this.addressCountry = addressCountry;
    }

    public String getAddressCountry() {
        return addressCountry;
    }

    public void setAddressProvince(String addressProvince) {
        this.addressProvince = addressProvince;
    }

    public String getAddressProvince() {
        return addressProvince;
    }

    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    public String getAddressCity() {
        return addressCity;
    }

    public void setAddressZone(String addressZone) {
        this.addressZone = addressZone;
    }

    public String getAddressZone() {
        return addressZone;
    }

    public void setAddressDetails(String addressDetails) {
        this.addressDetails = addressDetails;
    }

    public String getAddressDetails() {
        return addressDetails;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhone() {
        return phone;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getWebsite() {
        return website;
    }

    public void setIsListed(String isListed) {
        this.isListed = isListed;
    }

    public String getIsListed() {
        return isListed;
    }

    public void setOtherDescription(String otherDescription) {
        this.otherDescription = otherDescription;
    }

    public String getOtherDescription() {
        return otherDescription;
    }

    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }

    public List<CustomerContact> getCustomerContacts() {
        return customerContacts;
    }

    public void setCustomerContacts(List<CustomerContact> customerContacts) {
        this.customerContacts = customerContacts;
    }

    public String getParentCustomerName() {
        return parentCustomerName;
    }

    public void setParentCustomerName(String parentCustomerName) {
        this.parentCustomerName = parentCustomerName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
